In [9]:
import pandas as pd

caminho = "../data/raw/"
itens_prova = pd.read_csv("../data/raw/ITENS_PROVA_2024.csv", encoding="ISO-8859-1", sep=";")
participantes = pd.read_csv("../data/raw/PARTICIPANTES_2024.csv", encoding="ISO-8859-1", sep=";")
resultados = pd.read_csv("../data/raw/RESULTADOS_2024.csv", encoding="ISO-8859-1", sep=";")

print("\nITENS PROVA")
display(itens_prova)
print("\nPARTICIPANTES")
display(participantes)
print("\nRESULTADOS")
display(resultados)

ITENS PROVA

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
0,6,LC,150678,E,20,0,NaN,3.15898,0.16783,0.17207,AZUL,1395,NaN,0
1,7,LC,14475,D,1,0,NaN,2.36980,-0.23487,0.12324,AZUL,1353,NaN,0
2,7,LC,14475,D,1,0,NaN,2.36980,-0.23487,0.12324,AZUL,1441,NaN,0
3,7,LC,16575,A,16,0,NaN,3.04396,2.33757,0.08577,AMARELA,1354,NaN,0
4,7,LC,16575,A,16,0,NaN,3.04396,2.33757,0.08577,AMARELA,1442,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5545,176,MT,17549,E,8,0,NaN,3.53861,1.72953,0.05329,CINZA,1326,NaN,0
5546,176,MT,17549,E,8,0,NaN,3.53861,1.72953,0.05329,CINZA,1366,NaN,0
5547,176,MT,27923,A,19,0,NaN,3.29564,2.98287,0.14454,AMARELA,1324,NaN,0
5548,176,MT,27923,A,19,0,NaN,3.29564,2.98287,0.14454,AMARELA,1364,NaN,0
5549,176,MT,76177,D,1,0,NaN,2.73571,1.22835,0.14646,AMARELA,1408,NaN,0

PARTICIPANTES

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,...,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210062064233,2024,5,F,1,1,1,1,3,NaN,...,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,...,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,...,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,...,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,...,A,A,A,A,B,A,B,A,B,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4332939,210066495575,2024,7,M,1,1,1,1,2,NaN,...,A,B,A,A,B,A,B,A,C,A
4332940,210066495576,2024,6,M,1,3,1,3,0,NaN,...,A,A,A,A,C,A,B,A,C,A
4332941,210066495577,2024,4,F,1,2,1,1,1,NaN,...,A,B,B,A,B,A,B,B,B,A
4332942,210066495578,2024,2,F,1,3,1,2,0,NaN,...,A,A,A,A,B,A,A,A,B,A
4332943,210066495579,2024,1,F,1,1,1,3,0,NaN,...,B,B,A,A,B,B,B,A,D,D

RESULTADOS

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4332939,1966623,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,120.0,120.0,120.0,140.0,140.0,640.0
4332940,1661560,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,120.0,120.0,80.0,80.0,20.0,420.0
4332941,2464303,2024,35923874.0,3522505.0,Itapevi,35.0,SP,2.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,120.0,120.0,120.0,100.0,120.0,580.0
4332942,3164695,2024,33025150.0,3301306.0,Casimiro de Abreu,33.0,RJ,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4332943,3131550,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,120.0,180.0,140.0,160.0,180.0,780.0